### ISSUE TITLE
Account needs to be added as an external user in the tenant.

### ISSUE THREAD

**Issue by rogerbarreto** [anthonypuppo/skplayground#1]
When accessing https://skplayground.dev/playground and selecting my personal account to login

I get the following error. `Account needs to be added as an external user in the tenant.`

![image](https://github.com/anthonypuppo/skplayground/assets/19890735/6b713cc6-c56f-4a2d-96df-9956822186c1)

**Comment by anthonypuppo** [comment]
Thanks for catching, fixing...

**Comment by anthonypuppo** [comment]
Should be fixed now. Let me know if it's still causing you issues, needed to refactor a bit of the AD setup.

**Comment by rogerbarreto** [comment]
Fixed, congrats!
