### ISSUE TITLE
Hosting on Azure

### ISSUE THREAD

**Issue by EducatedAI-kaisera** [anthonypuppo/skplayground#2]
No issue with repo, just wondering what your experience has been hosting NextJS on Azure? How it been uneventful or any issues you've faced?

**Comment by anthonypuppo** [comment]
Definitely not as seamless as hosting using a dedicated Next.js provider like Vercel but if you don't mind a bit more manual setup it works just fine. For example, this projected is hosted on an Azure web app running Node.js v18.

FYI if thinking about hosting using Azure Static Web Apps you're currently limited to using Next.js pages routing. App router (like this project uses) isn't currently supported at the time of writing. See [here](https://github.com/Azure/static-web-apps/issues/1185) and [here](https://github.com/Azure/static-web-apps/issues/1209) for threads on this.
